import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div>
      <Head>
        <title>frontend task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div  className={styles.container}>
      
      <div className={styles.home_page}>
        <Link href="/hscode"><a className={styles.page_font}>HS Code</a></Link>
      </div>
      <div className={styles.home_page}>
        <Link href="/port"><a className={styles.page_font}>Port page</a></Link>
      </div>

      </div>

      <footer>
        <p className={styles.footer}>By - Shekhar | Pavan | Dinesh</p>
      </footer>
      
    </div>
  )
}
