import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>frontend task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div>
      <Link href="/hscode"><a>hs code</a></Link>
       </div>
       <div>
       <Link href="/port"><a>port page</a></Link>
       </div>
    </div>
  )
}
